# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:\Documents\Uni\year 3\diss\pyMD5\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.mouseCaptureRegion = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.mouseCaptureRegion.setEnabled(True)
        self.mouseCaptureRegion.setTitle("")
        self.mouseCaptureRegion.setObjectName("mouseCaptureRegion")
        self.progressBar = QtWidgets.QProgressBar(self.mouseCaptureRegion)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(0, 160, 481, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.hashCombo = QtWidgets.QComboBox(self.mouseCaptureRegion)
        self.hashCombo.setGeometry(QtCore.QRect(0, 190, 81, 19))
        self.hashCombo.setAutoFillBackground(False)
        self.hashCombo.setMaxVisibleItems(5)
        self.hashCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.hashCombo.setObjectName("hashCombo")
        self.hashCombo.addItem("")
        self.hashCombo.addItem("")
        self.hashInput = QtWidgets.QLineEdit(self.mouseCaptureRegion)
        self.hashInput.setGeometry(QtCore.QRect(90, 190, 181, 20))
        self.hashInput.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hashInput.setInputMask("")
        self.hashInput.setText("")
        self.hashInput.setDragEnabled(True)
        self.hashInput.setObjectName("hashInput")
        self.loadFileButton = QtWidgets.QPushButton(self.mouseCaptureRegion)
        self.loadFileButton.setGeometry(QtCore.QRect(370, 200, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.loadFileButton.setFont(font)
        self.loadFileButton.setObjectName("loadFileButton")
        self.randomKeyButton = QtWidgets.QPushButton(self.mouseCaptureRegion)
        self.randomKeyButton.setGeometry(QtCore.QRect(370, 180, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.randomKeyButton.setFont(font)
        self.randomKeyButton.setObjectName("randomKeyButton")
        self.hashButton = QtWidgets.QPushButton(self.mouseCaptureRegion)
        self.hashButton.setGeometry(QtCore.QRect(280, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hashButton.setFont(font)
        self.hashButton.setObjectName("hashButton")
        self.gridLayout.addWidget(self.mouseCaptureRegion, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(500, 10, 401, 231))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.inputBinaryText = QtWidgets.QLineEdit(self.groupBox)
        self.inputBinaryText.setGeometry(QtCore.QRect(150, 50, 231, 20))
        self.inputBinaryText.setReadOnly(True)
        self.inputBinaryText.setObjectName("inputBinaryText")
        self.blockText = QtWidgets.QTextEdit(self.groupBox)
        self.blockText.setGeometry(QtCore.QRect(10, 110, 371, 111))
        self.blockText.setReadOnly(True)
        self.blockText.setObjectName("blockText")
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 881, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 831, 271))
        self.widget.setObjectName("widget")
        self.exportButton = QtWidgets.QPushButton(self.tab)
        self.exportButton.setGeometry(QtCore.QRect(420, 290, 71, 20))
        self.exportButton.setObjectName("exportButton")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(490, 100, 221, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.fBufferVal = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fBufferVal.setFont(font)
        self.fBufferVal.setReadOnly(True)
        self.fBufferVal.setObjectName("fBufferVal")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fBufferVal)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.gBufferVal = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gBufferVal.setFont(font)
        self.gBufferVal.setReadOnly(True)
        self.gBufferVal.setObjectName("gBufferVal")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gBufferVal)
        self.loopCountLabel = QtWidgets.QLabel(self.layoutWidget)
        self.loopCountLabel.setObjectName("loopCountLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loopCountLabel)
        self.progressSlider = QtWidgets.QSlider(self.tab)
        self.progressSlider.setEnabled(False)
        self.progressSlider.setGeometry(QtCore.QRect(218, 240, 471, 16))
        self.progressSlider.setMinimum(1)
        self.progressSlider.setMaximum(5)
        self.progressSlider.setProperty("value", 1)
        self.progressSlider.setOrientation(QtCore.Qt.Horizontal)
        self.progressSlider.setObjectName("progressSlider")
        self.workingWordText = QtWidgets.QLineEdit(self.tab)
        self.workingWordText.setGeometry(QtCore.QRect(30, 40, 771, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.workingWordText.setFont(font)
        self.workingWordText.setReadOnly(True)
        self.workingWordText.setObjectName("workingWordText")
        self.loopCountLabel_2 = QtWidgets.QLabel(self.tab)
        self.loopCountLabel_2.setGeometry(QtCore.QRect(30, 20, 201, 16))
        self.loopCountLabel_2.setObjectName("loopCountLabel_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 100, 311, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.bBufferVal = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bBufferVal.setFont(font)
        self.bBufferVal.setReadOnly(True)
        self.bBufferVal.setObjectName("bBufferVal")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bBufferVal)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cBufferVal = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cBufferVal.setFont(font)
        self.cBufferVal.setReadOnly(True)
        self.cBufferVal.setObjectName("cBufferVal")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cBufferVal)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.dBufferVal = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dBufferVal.setFont(font)
        self.dBufferVal.setReadOnly(True)
        self.dBufferVal.setObjectName("dBufferVal")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dBufferVal)
        self.aBufferVal = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.aBufferVal.setFont(font)
        self.aBufferVal.setReadOnly(True)
        self.aBufferVal.setObjectName("aBufferVal")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aBufferVal)
        self.outputText = QtWidgets.QLineEdit(self.tab)
        self.outputText.setGeometry(QtCore.QRect(228, 260, 451, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.outputText.setFont(font)
        self.outputText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.outputText.setAutoFillBackground(False)
        self.outputText.setAlignment(QtCore.Qt.AlignCenter)
        self.outputText.setReadOnly(True)
        self.outputText.setObjectName("outputText")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.md5graphiclabel = QtWidgets.QLabel(self.tab_2)
        self.md5graphiclabel.setGeometry(QtCore.QRect(10, 10, 861, 389))
        self.md5graphiclabel.setText("")
        self.md5graphiclabel.setObjectName("md5graphiclabel")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 17))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.hashCombo.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hashCombo.setItemText(0, _translate("MainWindow", "MD5"))
        self.hashCombo.setItemText(1, _translate("MainWindow", "SHA-1"))
        self.hashInput.setPlaceholderText(_translate("MainWindow", "Enter Input to be Hashed"))
        self.loadFileButton.setText(_translate("MainWindow", "Load File"))
        self.randomKeyButton.setText(_translate("MainWindow", "Generate Random Key"))
        self.hashButton.setText(_translate("MainWindow", "Hash Message"))
        self.groupBox.setTitle(_translate("MainWindow", "Constants"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.label_13.setText(_translate("MainWindow", "F"))
        self.label_14.setText(_translate("MainWindow", "g"))
        self.loopCountLabel.setText(_translate("MainWindow", "Loop Count : "))
        self.loopCountLabel_2.setText(_translate("MainWindow", "Current Operational Block"))
        self.label_9.setText(_translate("MainWindow", "Buffer A"))
        self.label_10.setText(_translate("MainWindow", "Buffer B"))
        self.label_11.setText(_translate("MainWindow", "Buffer C"))
        self.label_12.setText(_translate("MainWindow", "Buffer D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main Loop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Graphical View"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

