# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:\Documents\Uni\year 3\diss\pyMD5\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.hashButton = QtWidgets.QPushButton(self.centralwidget)
        self.hashButton.setGeometry(QtCore.QRect(380, 10, 51, 20))
        self.hashButton.setObjectName("hashButton")
        self.hashInput = QtWidgets.QLineEdit(self.centralwidget)
        self.hashInput.setGeometry(QtCore.QRect(170, 10, 191, 20))
        self.hashInput.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hashInput.setInputMask("")
        self.hashInput.setText("")
        self.hashInput.setDragEnabled(True)
        self.hashInput.setObjectName("hashInput")
        self.hashCombo = QtWidgets.QComboBox(self.centralwidget)
        self.hashCombo.setGeometry(QtCore.QRect(70, 10, 81, 19))
        self.hashCombo.setAutoFillBackground(False)
        self.hashCombo.setMaxVisibleItems(5)
        self.hashCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.hashCombo.setObjectName("hashCombo")
        self.hashCombo.addItem("")
        self.hashCombo.addItem("")
        self.inputBinaryText = QtWidgets.QLineEdit(self.centralwidget)
        self.inputBinaryText.setGeometry(QtCore.QRect(210, 60, 221, 20))
        self.inputBinaryText.setReadOnly(True)
        self.inputBinaryText.setObjectName("inputBinaryText")
        self.blockText = QtWidgets.QTextEdit(self.centralwidget)
        self.blockText.setGeometry(QtCore.QRect(70, 90, 361, 51))
        self.blockText.setReadOnly(True)
        self.blockText.setObjectName("blockText")
        self.loopCountLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.loopCountLabel_4.setGeometry(QtCore.QRect(80, 60, 121, 16))
        self.loopCountLabel_4.setObjectName("loopCountLabel_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(460, 40, 171, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(80, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(80, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 160, 601, 241))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(330, 110, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(50, 70, 16, 16))
        self.label_9.setObjectName("label_9")
        self.workingWordText = QtWidgets.QLineEdit(self.groupBox_2)
        self.workingWordText.setGeometry(QtCore.QRect(90, 40, 501, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.workingWordText.setFont(font)
        self.workingWordText.setReadOnly(True)
        self.workingWordText.setObjectName("workingWordText")
        self.aBufferVal = QtWidgets.QLineEdit(self.groupBox_2)
        self.aBufferVal.setGeometry(QtCore.QRect(90, 70, 151, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.aBufferVal.setFont(font)
        self.aBufferVal.setReadOnly(True)
        self.aBufferVal.setObjectName("aBufferVal")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(50, 110, 16, 16))
        self.label_11.setObjectName("label_11")
        self.gBufferVal = QtWidgets.QLineEdit(self.groupBox_2)
        self.gBufferVal.setGeometry(QtCore.QRect(350, 110, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gBufferVal.setFont(font)
        self.gBufferVal.setReadOnly(True)
        self.gBufferVal.setObjectName("gBufferVal")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(50, 130, 16, 16))
        self.label_12.setObjectName("label_12")
        self.dBufferVal = QtWidgets.QLineEdit(self.groupBox_2)
        self.dBufferVal.setGeometry(QtCore.QRect(90, 130, 151, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dBufferVal.setFont(font)
        self.dBufferVal.setReadOnly(True)
        self.dBufferVal.setObjectName("dBufferVal")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(330, 70, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.loopCountLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.loopCountLabel_2.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.loopCountLabel_2.setObjectName("loopCountLabel_2")
        self.bBufferVal = QtWidgets.QLineEdit(self.groupBox_2)
        self.bBufferVal.setGeometry(QtCore.QRect(90, 90, 151, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bBufferVal.setFont(font)
        self.bBufferVal.setReadOnly(True)
        self.bBufferVal.setObjectName("bBufferVal")
        self.cBufferVal = QtWidgets.QLineEdit(self.groupBox_2)
        self.cBufferVal.setGeometry(QtCore.QRect(90, 110, 151, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cBufferVal.setFont(font)
        self.cBufferVal.setReadOnly(True)
        self.cBufferVal.setObjectName("cBufferVal")
        self.loopCountLabel = QtWidgets.QLabel(self.groupBox_2)
        self.loopCountLabel.setGeometry(QtCore.QRect(290, 20, 111, 16))
        self.loopCountLabel.setObjectName("loopCountLabel")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(50, 90, 16, 16))
        self.label_10.setObjectName("label_10")
        self.fBufferVal = QtWidgets.QLineEdit(self.groupBox_2)
        self.fBufferVal.setGeometry(QtCore.QRect(350, 70, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fBufferVal.setFont(font)
        self.fBufferVal.setReadOnly(True)
        self.fBufferVal.setObjectName("fBufferVal")
        self.progressSlider = QtWidgets.QSlider(self.groupBox_2)
        self.progressSlider.setGeometry(QtCore.QRect(80, 180, 461, 16))
        self.progressSlider.setMaximum(5)
        self.progressSlider.setProperty("value", 2)
        self.progressSlider.setOrientation(QtCore.Qt.Horizontal)
        self.progressSlider.setObjectName("progressSlider")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 420, 601, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.outputText = QtWidgets.QLineEdit(self.groupBox_3)
        self.outputText.setGeometry(QtCore.QRect(30, 30, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.outputText.setFont(font)
        self.outputText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.outputText.setAutoFillBackground(False)
        self.outputText.setAlignment(QtCore.Qt.AlignCenter)
        self.outputText.setReadOnly(True)
        self.outputText.setObjectName("outputText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 17))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.hashCombo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hashButton.setText(_translate("MainWindow", "Hash"))
        self.hashInput.setPlaceholderText(_translate("MainWindow", "Enter Input to be Hashed"))
        self.hashCombo.setItemText(0, _translate("MainWindow", "MD5"))
        self.hashCombo.setItemText(1, _translate("MainWindow", "SHA-1"))
        self.loopCountLabel_4.setText(_translate("MainWindow", "Binary Representation"))
        self.groupBox.setTitle(_translate("MainWindow", "Constants"))
        self.label_4.setText(_translate("MainWindow", "Word Size"))
        self.label_7.setText(_translate("MainWindow", "32 bits"))
        self.label_3.setText(_translate("MainWindow", "Block Size"))
        self.label_6.setText(_translate("MainWindow", "512 bits"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Main Loop"))
        self.label_14.setText(_translate("MainWindow", "g"))
        self.label_9.setText(_translate("MainWindow", "a0"))
        self.label_11.setText(_translate("MainWindow", "c0"))
        self.label_12.setText(_translate("MainWindow", "d0"))
        self.label_13.setText(_translate("MainWindow", "F"))
        self.loopCountLabel_2.setText(_translate("MainWindow", "Current Word"))
        self.loopCountLabel.setText(_translate("MainWindow", "Loop Count : "))
        self.label_10.setText(_translate("MainWindow", "b0"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

